<a href="https://colab.research.google.com/github/gagan-iitb/DSP505/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

o = np.matmul(a, b)

print(o)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


Output the transpose of a matrix (as numpy array)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

a_transpose = a.T

print(a_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [ ]:


# Initialize the arrays
array1 = np.array([[1, 2, 3]])  # Shape (1, 3)
array2 = np.array([[4], [5], [6]])  # Shape (3, 1)

# Use numpy's broadcasting feature to ensure the shapes match
# Sum using an iterator
result = np.zeros((3, 3))  # Initialize the result array with shape (3, 3)

for i in range(array1.shape[1]):
    for j in range(array2.shape[0]):
        result[j, i] = array1[0, i] + array2[j, 0]
print("Result:\n", result)

Result:
 [[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [ ]:
#Alternate solution using numpy nditer

# Initialize the arrays
A = np.array([[1, 2, 3]])
B = np.array([[4], [5], [6]])

# Create an nditer object for the arrays A and B, and an uninitialized output array
it = np.nditer([A, B, None])

# Iterate over the arrays element-wise and store the result in the third operand (output array)
for x, y, z in it:
    z[...] = x + y

# Print the output array (third operand in the nditer object)
print(it.operands[2])

[[5 6 7]
 [6 7 8]
 [7 8 9]]


Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Numpy program to convert a given list into an array, then again convert it into a list. Check initial list and final list a

In [ ]:
a = [[1, 2], [3, 4]]

# Converting the nested list 'a' into a NumPy array 'x' using np.array()
x = np.array(a)

# Converting the NumPy array 'x' back to a Python nested list 'a2' using the tolist() method
a2 = x.tolist()
print(a == a2)

True


Numpy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [ ]:
# Creating a 10x10 matrix filled with ones using np.ones()
x = np.ones((10, 10))

# Setting the inner values of the matrix 'x' (excluding the borders) to 0 using slicing
x[1:-1, 1:-1] = 0

# Printing the modified matrix 'x'
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Given a 2D NumPy array A of shape (3, 3), rotate the matrix 90 degree clockwise

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(np.rot90(A, -1))

[[7 4 1]
 [8 5 2]
 [9 6 3]]


Given a 2D NumPy array A of shape (3,3),print the sum of all the elements on both the main diagonal and the anti-diagonal.



In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
main_diag_sum = np.trace(A)
anti_diag_sum = np.trace(np.fliplr(A))
print(main_diag_sum + anti_diag_sum)

30


Given a 2D NumPy array A, extract all unique elements from the array, counts the occurrences of each unique element, and print a 2D array where each row consists of a unique element and its corresponding count, sorted by the unique element in ascending order.



In [ ]:
A = np.array([[3, 5, 2, 3],
              [7, 3, 5, 2],
              [9, 2, 5, 7]])
unique, counts = np.unique(A, return_counts=True)
result = np.column_stack((unique, counts))
print(result)

[[2 3]
 [3 3]
 [5 3]
 [7 2]
 [9 1]]


Given a 4X4 array, swap rows and columns of a given array in reverse order.


In [ ]:
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])

# Reversing both rows and columns using [::-1, ::-1]
new_nums = nums[::-1, ::-1]

# Printing the new array after swapping rows and columns in reverse order
print("\nSwap rows and columns of the said array in reverse order:")
print(new_nums)


Swap rows and columns of the said array in reverse order:
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]


**`Exercises`**

Q1. Given a  NumPy array A of shape (3, 3), normalize each row so that the sum of elements in each row equals 1.


In [ ]:
#write your code here

Q2. Given a 2D NumPy array A,remove any row in the array that contains a NaN value.

In [ ]:
#write your code here

Q3. Given a 2D NumPy array A,print a 1D array containing the indices of the maximum value in each row.

In [ ]:
#write your code here

Q4.Given two arrays,calculate the covariance matrix of the given two arrays

In [ ]:
#write your code here

Q5.Given a 1D NumPy array A and an integer k,computes the moving average of the array with a window size k

In [ ]:
#write your code here

Q6.How is arr[:,0] different from arr[:,[0]].Show it with the help of example

In [ ]:
#write your code here

Q7.Given a 2D NumPy array A of shape (m, n), create a function transform_matrix(A) that performs the following operations:

For each element in the array, if the element is in the even row index (0, 2, 4,...), square the element.
For each element in the odd row index (1, 3, 5,...), multiply the element by 3 and add 1.
After modifying the elements based on the above rules, normalize the entire matrix so that the maximum value in the matrix becomes 1 and the minimum value becomes 0

In [ ]:
#write your code here

Q8.Given two 2D NumPy arrays A of shape (m, n) and B of shape (p, n), write a function  that performs a custom matrix multiplication where each element (i, j) of the resulting matrix C is the sum of element-wise products between the ith row of A and the jth row of B, but only for the first k elements of each row, where k = min(m, n, p).

In [ ]:
#write your code here

Q9.Show the difference between **ndarray** and **array** in numpy with the help of example

In [ ]:
#write your code here

Q10.Write a code to convert an image to numpy array and save it to csv file using python

In [ ]:
#write your code here